<?php

 $title = 'Adiciona nova pessoa';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('pessoa-acao', array('controller' => 'pessoas' ,'action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nome'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
