<?php

$title = 'Lista de Registros';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>
     <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
       Novo Registro
     </button>
 </p>



 <!-- Modal -->
 <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
         <h4 class="modal-title" id="myModalLabel">Nova Cadastro</h4>
       </div>
       <div class="modal-body">
         <?php

         $form->setAttribute('action', $this->url('pessoa-acao', array('controller' => 'pessoas' ,'action' => 'add')));
         $form->prepare();
         echo $this->form()->openTag($form);
         echo $this->formHidden($form->get('id'));
         echo $this->formRow($form->get('nome'));
         echo $this->formSubmit($form->get('submit'));
         echo $this->form()->closeTag();

         ?>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       </div>
     </div>
   </div>
 </div>

 <div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
         <h4 class="modal-title">Editar Registro</h4>
       </div>
       <div class="modal-body">

       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-default" type="submit" data-dismiss="modal" >Close</button>
       </div>
     </div>
   </div>
 </div>



 <!-- Modal Dialog -->
 <div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
         <h4 class="modal-title">Deletar</h4>
       </div>
       <div class="modal-body">
         <p></p>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
         <button type="button" class="btn btn-danger" id="confirm">Delete</button>
       </div>
     </div>
   </div>
 </div>

 <table class="table">
 <tr>
     <th>Id</th>
     <th>Nome</th>
     <th>Editar</th>
     <th>Deletar</th>
 </tr>
 <?php foreach ($data as $pessoa) : ?>
 <tr>
     <td id="id_edit"><?php echo $this->escapeHtml($pessoa['id']);?></td>
     <td id="nome_edit"><?php echo $this->escapeHtml($pessoa['nome']);?></td>
     <td>
       <button type="button" class="btn btn-xs btn-info" data-toggle="modal" data-target="#modal-edit">
           <i class="glyphicon glyphicon-edit"></i> Editar
       </button>
     </td>
    <td>
         <form method="POST" action="<?php echo $this->url('pessoa-acao', array('controller'=>'pessoas','action'=>'delete', 'id' => $pessoa['id']));?>" accept-charset="UTF-8" style="display:inline">
           <button class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete User" data-message="Você quer deletar o <?php echo $pessoa['nome'] ?>?">
               <i class="glyphicon glyphicon-trash"></i> Deletar
           </button>
          </form>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 <?php echo $this->paginationControl($this->data,'Sliding','paginator', array('route' => 'pessoas')); ?>
